buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // අපි Android Plugin එක 7.4.0 වලට අඩු කළා (Gradle 7.6.1 එකත් එක්ක වැඩ කරන්න)
        classpath 'com.android.tools.build:gradle:7.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
