plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.colo'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.colo"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    // මෙතන VERSION_17 වෙනුවට VERSION_1_8 හෝ VERSION_11 දාන්න (ඔබේ කෝඩ් එක Java 8 හෝ 11 නම්)
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
